// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/addition.proto

/*
Package addition is a generated protocol buffer package.

It is generated from these files:
	proto/addition.proto

It has these top-level messages:
	AddRequest
	AddResponse
*/
package addition

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddRequest struct {
	A int64 `protobuf:"varint,1,opt,name=a" json:"a,omitempty"`
	B int64 `protobuf:"varint,2,opt,name=b" json:"b,omitempty"`
}

func (m *AddRequest) Reset()                    { *m = AddRequest{} }
func (m *AddRequest) String() string            { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()               {}
func (*AddRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddRequest) GetA() int64 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *AddRequest) GetB() int64 {
	if m != nil {
		return m.B
	}
	return 0
}

type AddResponse struct {
	Rez int64 `protobuf:"varint,1,opt,name=rez" json:"rez,omitempty"`
}

func (m *AddResponse) Reset()                    { *m = AddResponse{} }
func (m *AddResponse) String() string            { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()               {}
func (*AddResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddResponse) GetRez() int64 {
	if m != nil {
		return m.Rez
	}
	return 0
}

func init() {
	proto.RegisterType((*AddRequest)(nil), "addition.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "addition.AddResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AdditionService service

type AdditionServiceClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
}

type additionServiceClient struct {
	cc *grpc.ClientConn
}

func NewAdditionServiceClient(cc *grpc.ClientConn) AdditionServiceClient {
	return &additionServiceClient{cc}
}

func (c *additionServiceClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := grpc.Invoke(ctx, "/addition.AdditionService/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AdditionService service

type AdditionServiceServer interface {
	Add(context.Context, *AddRequest) (*AddResponse, error)
}

func RegisterAdditionServiceServer(s *grpc.Server, srv AdditionServiceServer) {
	s.RegisterService(&_AdditionService_serviceDesc, srv)
}

func _AdditionService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdditionServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/addition.AdditionService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdditionServiceServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdditionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "addition.AdditionService",
	HandlerType: (*AdditionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _AdditionService_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/addition.proto",
}

func init() { proto.RegisterFile("proto/addition.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4c, 0x49, 0xc9, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x03, 0x73, 0x85, 0x38, 0x60,
	0x7c, 0x25, 0x0d, 0x2e, 0x2e, 0xc7, 0x94, 0x94, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21,
	0x1e, 0x2e, 0xc6, 0x44, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0xc6, 0x44, 0x10, 0x2f, 0x49,
	0x82, 0x09, 0xc2, 0x4b, 0x52, 0x92, 0xe7, 0xe2, 0x06, 0xab, 0x2c, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e,
	0x15, 0x12, 0xe0, 0x62, 0x2e, 0x4a, 0xad, 0x82, 0x2a, 0x06, 0x31, 0x8d, 0xdc, 0xb9, 0xf8, 0x1d,
	0xa1, 0xc6, 0x06, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x0a, 0x99, 0x70, 0x31, 0x3b, 0xa6, 0xa4,
	0x08, 0x89, 0xe8, 0xc1, 0xed, 0x47, 0x58, 0x26, 0x25, 0x8a, 0x26, 0x0a, 0x31, 0x58, 0x89, 0xc1,
	0x89, 0x37, 0x8a, 0xbb, 0x20, 0x09, 0xee, 0xe4, 0x24, 0x36, 0xb0, 0x9b, 0x8d, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x6c, 0xce, 0x96, 0x53, 0xcb, 0x00, 0x00, 0x00,
}
