// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/multiplication.proto

/*
Package multiplication is a generated protocol buffer package.

It is generated from these files:
	proto/multiplication.proto

It has these top-level messages:
	MulRequest
	MulResponse
*/
package multiplication

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MulRequest struct {
	A int64 `protobuf:"varint,1,opt,name=a" json:"a,omitempty"`
	B int64 `protobuf:"varint,2,opt,name=b" json:"b,omitempty"`
}

func (m *MulRequest) Reset()                    { *m = MulRequest{} }
func (m *MulRequest) String() string            { return proto.CompactTextString(m) }
func (*MulRequest) ProtoMessage()               {}
func (*MulRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MulRequest) GetA() int64 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *MulRequest) GetB() int64 {
	if m != nil {
		return m.B
	}
	return 0
}

type MulResponse struct {
	Rez int64 `protobuf:"varint,1,opt,name=rez" json:"rez,omitempty"`
}

func (m *MulResponse) Reset()                    { *m = MulResponse{} }
func (m *MulResponse) String() string            { return proto.CompactTextString(m) }
func (*MulResponse) ProtoMessage()               {}
func (*MulResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MulResponse) GetRez() int64 {
	if m != nil {
		return m.Rez
	}
	return 0
}

func init() {
	proto.RegisterType((*MulRequest)(nil), "multiplication.MulRequest")
	proto.RegisterType((*MulResponse)(nil), "multiplication.MulResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MultiplicationService service

type MultiplicationServiceClient interface {
	Mul(ctx context.Context, in *MulRequest, opts ...grpc.CallOption) (*MulResponse, error)
}

type multiplicationServiceClient struct {
	cc *grpc.ClientConn
}

func NewMultiplicationServiceClient(cc *grpc.ClientConn) MultiplicationServiceClient {
	return &multiplicationServiceClient{cc}
}

func (c *multiplicationServiceClient) Mul(ctx context.Context, in *MulRequest, opts ...grpc.CallOption) (*MulResponse, error) {
	out := new(MulResponse)
	err := grpc.Invoke(ctx, "/multiplication.MultiplicationService/Mul", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MultiplicationService service

type MultiplicationServiceServer interface {
	Mul(context.Context, *MulRequest) (*MulResponse, error)
}

func RegisterMultiplicationServiceServer(s *grpc.Server, srv MultiplicationServiceServer) {
	s.RegisterService(&_MultiplicationService_serviceDesc, srv)
}

func _MultiplicationService_Mul_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MulRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiplicationServiceServer).Mul(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/multiplication.MultiplicationService/Mul",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiplicationServiceServer).Mul(ctx, req.(*MulRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MultiplicationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "multiplication.MultiplicationService",
	HandlerType: (*MultiplicationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Mul",
			Handler:    _MultiplicationService_Mul_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/multiplication.proto",
}

func init() { proto.RegisterFile("proto/multiplication.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x2d, 0xcd, 0x29, 0xc9, 0x2c, 0xc8, 0xc9, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf,
	0xd3, 0x03, 0x0b, 0x0a, 0xf1, 0xa1, 0x8a, 0x2a, 0x69, 0x70, 0x71, 0xf9, 0x96, 0xe6, 0x04, 0xa5,
	0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xf1, 0x70, 0x31, 0x26, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x30,
	0x07, 0x31, 0x26, 0x82, 0x78, 0x49, 0x12, 0x4c, 0x10, 0x5e, 0x92, 0x92, 0x3c, 0x17, 0x37, 0x58,
	0x65, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x00, 0x17, 0x73, 0x51, 0x6a, 0x15, 0x54, 0x31,
	0x88, 0x69, 0x14, 0xc9, 0x25, 0xea, 0x8b, 0x62, 0x78, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa,
	0x90, 0x03, 0x17, 0xb3, 0x6f, 0x69, 0x8e, 0x90, 0x94, 0x1e, 0x9a, 0x8b, 0x10, 0x16, 0x4b, 0x49,
	0x63, 0x95, 0x83, 0x58, 0xa5, 0xc4, 0xe0, 0x24, 0x1c, 0x25, 0x58, 0x90, 0x84, 0xe6, 0xa1, 0x24,
	0x36, 0xb0, 0x8f, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xdd, 0x4c, 0x5b, 0xef, 0x00,
	0x00, 0x00,
}
